spring:
    application:
        name: your-application-name

    datasource:
        url: jdbc:mysql://localhost:3306/your-database
        username: your-username
        password: your-password
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5Dialect

    main:
        banner-mode: "off"

springdoc:
    api-docs:
        enabled: true  # API 문서 생성 활성화
    swagger-ui:
        enabled: true  # Swagger UI 활성화
        path: /swagger-ui.html  # Swagger UI 접근 경로
        urls:
            - url: /v3/api-docs  # API 문서 경로
